# Generated by Django 5.2.10 on 2026-02-05 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_uri', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scopes', models.TextField()),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('google_sheet_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('google_url', models.URLField()),
                ('share_token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('columns', models.JSONField(default=list)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_syncing', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row_number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sheets.sheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sheet_row_number'],
            },
        ),
        migrations.CreateModel(
            name='SheetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=64)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='sheets.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='SheetSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('db', 'DB'), ('sheet', 'Sheet')], default='db', max_length=10)),
                ('fingerprint', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheets.sheetrow')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='sheets.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('db_payload', models.JSONField()),
                ('google_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sheets.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='SheetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sheets.sheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sheet', 'user'], name='sheets_shee_sheet_i_6336b8_idx')],
                'unique_together': {('sheet', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['sheet', 'sheet_row_number'], name='sheets_shee_sheet_i_6953c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sheetrow',
            unique_together={('sheet', 'sheet_row_number')},
        ),
        migrations.AddIndex(
            model_name='sheetsyncevent',
            index=models.Index(fields=['sheet', 'processed'], name='sheets_shee_sheet_i_b30baa_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetsyncevent',
            index=models.Index(fields=['fingerprint'], name='sheets_shee_fingerp_b7daa1_idx'),
        ),
    ]
