# Generated by Django 5.2.10 on 2026-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetrow',
            name='sheet_row_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
