# Generated by Django 5.2.10 on 2026-03-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_alter_sheetrow_sheet_row_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmember',
            name='role',
            field=models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer'), ('collaborator', 'Collaborator')], default='editor', max_length=15),
        ),
    ]
