# Generated by Django 5.2.10 on 2026-04-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0004_remove_sheetrow_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheetmember",
            name="role",
            field=models.CharField(
                choices=[("collaborator", "Collaborator"), ("joinee", "Joinee")],
                default="joinee",
                max_length=15,
            ),
        ),
    ]
