# Generated by Django 5.2.10 on 2026-04-02 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0005_rename_roles_to_collaborator_joinee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("sheet_created", "Created sheet"),
                            ("row_added", "Added a row to"),
                            ("row_updated", "Updated a row in"),
                            ("row_deleted", "Deleted a row from"),
                            ("member_joined", "Joined"),
                            ("collaborator_added", "Added as collaborator to"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="sheets.sheet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="sheets_acti_user_id_50625c_idx",
                    ),
                    models.Index(
                        fields=["sheet", "-created_at"],
                        name="sheets_acti_sheet_i_85fb9f_idx",
                    ),
                ],
            },
        ),
    ]
