# Generated by Django 5.2.10 on 2026-04-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0007_add_sheet_column"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sheetcolumn",
            new_name="sheets_shee_sheet_i_609432_idx",
            old_name="sheets_shee_sheet_i_pos_idx",
        ),
        migrations.AddField(
            model_name="sheet",
            name="sync_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
