# Generated by Django 5.2.10 on 2026-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sheets",
            "0008_rename_sheets_shee_sheet_i_pos_idx_sheets_shee_sheet_i_609432_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sheetrow",
            name="tab_row_numbers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
