# Generated by Django 5.2.10 on 2026-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0009_sheetrow_tab_row_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="is_live",
            field=models.BooleanField(default=True),
        ),
    ]
